name: 'Create a discussion'
description: 'Create a repo discussion on GitHub'
inputs:
  category:
    description: 'Discussion category to create the discussion in'
    required: false
  filename:
    description: 'Filepath to the markdown template for the discussion'
    required: false
  title:
    description: 'Title for the discussion'
    required: true
  title-date:
    description: 'Pass `true` to include the date in the discussion title'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
